---
- name: 创建 {{ rke2_server.db.group }} 组
  group:
    name: "{{ rke2_server.db.group }}"
    gid: "{{ rke2_server.db.gid }}"
    system: yes

- name: 创建 {{ rke2_server.db.user }} 用户
  user:
    name: "{{ rke2_server.db.user }}"
    uid: "{{ rke2_server.db.uid }}"
    group: "{{ rke2_server.db.group }}"
    system: yes
    shell: /sbin/nologin
    create_home: no

- name: 配置 RKE2 SERVER 配置文件
  template: src=97-k8s-rke2-server-config.yml.j2 dest={{ global.rke2_worker_dir }}/config.yaml

- name: 部署 RKE2 SERVER 程序
  shell: INSTALL_RKE2_TYPE=server INSTALL_RKE2_ARTIFACT_PATH={{ global.software_dir }} sh {{ global.software_dir }}/install.sh

- name: 启动 RKE2 SERVER 初始化节点【首个 MASTER】
  systemd:
    name: rke2-server
    state: restarted
    enabled: yes
  when: init_master | default(false) | bool

- name: 获取集群初始化 RKE2 SERVER 节点
  set_fact:
    first_master_node: "{{ item }}"
  with_items: "{{ groups.rke2_server }}"
  when:
    - hostvars[item].init_master is defined
    - hostvars[item].init_master | bool
  run_once: true

- name: 等待 RKE2 SERVER 初始化, 启动 APIServer服务
  wait_for:
    host: "{{ hostvars[first_master_node].ansible_host }}"
    port: 6443
    timeout: 120
    delay: 5
  run_once: true
#  delegate_to: localhost

- name: 检查是否安装 CNI 插件
  stat:
    path: /opt/cni
  register: cni_dir

- name: 修改 /opt/cni 权限
  file:
    path: /opt/cni
    owner: root
    group: root
    recurse: true
  when:
    - init_master | default(false) | bool
    - cni_dir.stat.exists

- name: 启动额外的 RKE2 SERVER 服务
  systemd:
    name: rke2_server
    state: restarted
    enabled: yes
  when: not init_master | default(false) | bool

- name: 检查是否安装 CNI 插件
  stat:
    path: /opt/cni
  register: cni_dir

- name: 修改 /opt/cni 权限
  file:
    path: /opt/cni
    owner: root
    group: root
    recurse: true
  when:
    - not init_master | default(false) | bool
    - cni_dir.stat.exists
