---
- name: 创建 {{ global.k8s_user.user }} 用户的 .kube 目录
  file:
    path: "/home/{{ global.k8s_user.user }}/.kube"
    state: directory
    owner: "{{ global.k8s_user.user }}"
    group: "{{ global.k8s_user.group }}"
    mode: 0700

- name: 复制 RKE2 的 kubeconfig 文件到到 {{ global.k8s_user.user }} 用户的 .kube 目录
  copy:
    src: "{{ rke2_server.write_kubeconfig }}"
    dest: "/home/{{ global.k8s_user.user }}/.kube/config"
    owner: "{{ global.k8s_user.user }}"
    group: "{{ global.k8s_user.group }}"
    mode: "{{ rke2_server.write_kubeconfig_mode }}"
    remote_src: yes

- name: 修改 kubeconfig 文件权限, 属主, 所属组
  file:
    path: /home/{{ global.k8s_user.user }}/.kube/config
    owner: "{{ global.k8s_user.user }}"
    group: "{{ global.k8s_user.group }}"
    mode: "{{ rke2_server.write_kubeconfig_mode }}"

- name: 上传 helm 工具
  copy:
    src: helm
    dest: /usr/local/bin/helm
    mode: '0755'

- name: 更新 {{ global.k8s_user.user }} 用户的 K8S 环境变量块
  blockinfile:
    path: /home/{{ global.k8s_user.user }}/.bashrc
    marker: "# {mark} ANSIBLE K8S ENV"
    block: |
      PS1='\[\e[35m\]\u\[\e[m\]\[\e[97m\]\[\e[m\]\[\e[36m\]@\h\[\e[m\] \[\e[33m\]$(pwd):~\[\e[m\]\[\e[34m\] $\[\e[m\] '
      alias k='kubectl'
      export PATH=$PATH:{{ global.rke2_data_dir }}/bin/
      source <(crictl completion bash)
      source <(kubectl completion bash)
      source <(helm completion bash)
      complete -o default -F __start_kubectl k
    owner: "{{ global.k8s_user.user }}"
    group: "{{ global.k8s_user.group }}"
    mode: '0644'

- name: 加载 {{ global.k8s_user.user }} 用户的环境变量
  shell: source /home/{{ global.k8s_user.user }}/.bashrc
  args:
    executable: /bin/bash

