---
- name: 配置 RKE2 AGENT 配置文件
  template: src=97-k8s-rke2-agent-config.yml.j2 dest={{ global.rke2_worker_dir }}/config.yaml

- name: 部署 RKE2 AGENT 程序
  shell: INSTALL_RKE2_TYPE=agent INSTALL_RKE2_VERSION={{ rke2_version }} INSTALL_RKE2_ARTIFACT_PATH={{ global.software_dir }} sh {{ global.software_dir }}/install.sh

- name: 启动 RKE2 AGENT
  systemd:
    name: rke2-agent
    state: restarted
    enabled: yes

- name: 检查是否安装 CNI 插件
  stat:
    path: /opt/cni
  register: cni_dir

- name: 修改 /opt/cni 权限
  file:
    path: /opt/cni
    owner: root
    group: root
    recurse: true
