---
- name: 部署 rke2-server
  hosts: rke2_server
  vars_files:
    - "{{ inventory_dir }}/secrets.yml"
    - "{{ inventory_dir }}/site.yml"
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: "{{ servers[inventory_hostname].sudopass | b64decode }}"
  roles:
    - prepare
    - rke2-server
